minecraft_version=26.3

loader_version=0.18.4
loom_version=1.15-SNAPSHOT
fabric_api_version=0.152.1+26.2


mod_version=2.5
maven_group=top.msu333.welcomemod
archives_base_name=welcome_awa


org.gradle.java.home=C:\\Program Files\\Zulu\\zulu-25
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=true
