pluginManagement {
    repositories {
        maven {
            name = "Aliyun Gradle Plugin"
            url = "https://maven.aliyun.com/repository/gradle-plugin"
        }
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
    }
}

rootProject.name = "Motd_awa"